#!/usr/bin/env bash
#
# Refresh /data/coolify/proxy/dynamic/hashden-dev-lockdown.yaml with the
# current dev web + stratum container IPs. Traefik watches the dynamic
# directory and hot-reloads on file change, so the gate updates within
# seconds without a Traefik restart.
#
# Why this exists: Coolify recreates containers on every dev deploy, and
# the new containers get new IPs on the dev compose network. The file
# provider needs explicit upstream URLs (Coolify's auto-services aren't
# cross-provider-referenceable), so the IPs in the file go stale.
#
# Install:
#   scp this file to root@VPS:/usr/local/bin/hashden-update-dev-lockdown.sh
#   chmod +x /usr/local/bin/hashden-update-dev-lockdown.sh
#
# Run automatically (option A — host cron, polls every minute):
#   * * * * * /usr/local/bin/hashden-update-dev-lockdown.sh >> /var/log/hashden-lockdown.log 2>&1
#
# Run manually after a dev deploy:
#   ssh root@VPS /usr/local/bin/hashden-update-dev-lockdown.sh
#
# Exit codes:
#   0 = file updated (or already current — idempotent)
#   1 = dev containers not found (dev stack is down)
#   2 = couldn't write file

set -euo pipefail

DEV_UUID="bfezxkdfdjbomafdauywngxy"
TARGET="/data/coolify/proxy/dynamic/hashden-dev-lockdown.yaml"

web_ip=$(docker ps --filter "name=web-${DEV_UUID}" --format '{{.Names}}' | head -1 \
    | xargs -r -I{} docker inspect {} --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{"\n"}}{{end}}' \
    | grep -v '^$' | head -1)
stratum_ip=$(docker ps --filter "name=stratum-${DEV_UUID}" --format '{{.Names}}' | head -1 \
    | xargs -r -I{} docker inspect {} --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{"\n"}}{{end}}' \
    | grep -v '^$' | head -1)

if [[ -z "${web_ip:-}" || -z "${stratum_ip:-}" ]]; then
    echo "$(date -Is) ERR dev containers not found (web=${web_ip:-?} stratum=${stratum_ip:-?})" >&2
    exit 1
fi

new_content=$(cat <<EOF
# Auto-generated by /usr/local/bin/hashden-update-dev-lockdown.sh — do not hand-edit.
# Source of truth: infrastructure/coolify/traefik-hashden-dev-lockdown.yaml in the repo.
# Container IPs refreshed on every run; updated $(date -Is).

http:
  routers:
    hashden-dev-web-locked:
      entryPoints:
        - https
      rule: "Host(\`dev.hashden.app\`)"
      service: hashden-dev-web-svc
      middlewares:
        - tailscale-only
      priority: 1000
      tls:
        certResolver: letsencrypt

    hashden-dev-stratum-locked:
      entryPoints:
        - https
      rule: "Host(\`dev-api.hashden.app\`)"
      service: hashden-dev-stratum-svc
      middlewares:
        - tailscale-only
      priority: 1000
      tls:
        certResolver: letsencrypt

  services:
    hashden-dev-web-svc:
      loadBalancer:
        servers:
          - url: "http://${web_ip}:3000"

    hashden-dev-stratum-svc:
      loadBalancer:
        servers:
          - url: "http://${stratum_ip}:3334"
EOF
)

if [[ -f "$TARGET" ]] && diff -q <(echo "$new_content") "$TARGET" >/dev/null 2>&1; then
    # No-op when IPs haven't changed; keeps logs quiet under the per-minute cron.
    exit 0
fi

if ! echo "$new_content" > "$TARGET"; then
    echo "$(date -Is) ERR failed to write $TARGET" >&2
    exit 2
fi

echo "$(date -Is) OK refreshed web=${web_ip} stratum=${stratum_ip}"
