#!/usr/bin/env bash
#
# Refresh the file-provider routing configs that point at hashden's
# stratum + web containers by IP. Container IPs rotate on every Coolify
# redeploy (Docker recreates containers), and the two Traefik file
# configs below need explicit upstream URLs:
#
#   /data/coolify/proxy/dynamic/hashden-dev-lockdown.yaml
#     dev.hashden.app + dev-api.hashden.app, gated by tailscale-only
#
#   /data/coolify/proxy/dynamic/hashden-api-routes.yaml
#     api.hashden.app (prod), ungated, exists to sidestep the broken
#     shared `hashden-api@docker` service that Coolify can't make unique
#     per env (its ${VAR} interpolation in labels is escaped).
#
# Traefik watches the dynamic directory and hot-reloads on file change,
# so an update propagates within seconds without a Traefik restart.
#
# Install:
#   scp this file to root@VPS:/usr/local/bin/hashden-update-dev-lockdown.sh
#   chmod +x /usr/local/bin/hashden-update-dev-lockdown.sh
#
# Run automatically (host cron, polls every minute):
#   * * * * * /usr/local/bin/hashden-update-dev-lockdown.sh >> /var/log/hashden-lockdown.log 2>&1
#
# Conservative: if a stack is down, leave its file unchanged rather
# than emit a broken config. Routing for that env breaks (502) but
# returns the moment the stack comes back up + the next cron tick.

set -euo pipefail

DEV_UUID="bfezxkdfdjbomafdauywngxy"
PROD_UUID="owqo1dz0y7rwy04a4qt8ypm2"
DEV_TARGET="/data/coolify/proxy/dynamic/hashden-dev-lockdown.yaml"
PROD_TARGET="/data/coolify/proxy/dynamic/hashden-api-routes.yaml"

container_ip() {
    local name_pattern="$1"
    docker ps --filter "name=${name_pattern}" --format '{{.Names}}' | head -1 \
        | xargs -r -I{} docker inspect {} --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{"\n"}}{{end}}' \
        | grep -v '^$' | head -1
}

# Each block writes its file independently. If one stack is down we
# skip its file but still refresh the other; that keeps the working
# env's gate accurate even when the other env is mid-deploy.

# ---- dev (web + stratum, gated by tailscale-only) ----
dev_web_ip=$(container_ip "web-${DEV_UUID}" || true)
dev_stratum_ip=$(container_ip "stratum-${DEV_UUID}" || true)

if [[ -n "${dev_web_ip:-}" && -n "${dev_stratum_ip:-}" ]]; then
    new_dev=$(cat <<EOF
# Auto-generated by /usr/local/bin/hashden-update-dev-lockdown.sh — do not hand-edit.
# Source of truth: infrastructure/coolify/traefik-hashden-dev-lockdown.yaml in the repo.
# Container IPs refreshed on every run; updated $(date -Is).

http:
  routers:
    hashden-dev-web-locked:
      entryPoints:
        - https
      rule: "Host(\`dev.hashden.app\`)"
      service: hashden-dev-web-svc
      middlewares:
        - tailscale-only
      priority: 1000
      tls:
        certResolver: letsencrypt

    hashden-dev-stratum-locked:
      entryPoints:
        - https
      rule: "Host(\`dev-api.hashden.app\`)"
      service: hashden-dev-stratum-svc
      middlewares:
        - tailscale-only
      priority: 1000
      tls:
        certResolver: letsencrypt

  services:
    hashden-dev-web-svc:
      loadBalancer:
        servers:
          - url: "http://${dev_web_ip}:3000"

    hashden-dev-stratum-svc:
      loadBalancer:
        servers:
          - url: "http://${dev_stratum_ip}:3334"
EOF
)
    if [[ ! -f "$DEV_TARGET" ]] || ! diff -q <(echo "$new_dev") "$DEV_TARGET" >/dev/null 2>&1; then
        echo "$new_dev" > "$DEV_TARGET"
        echo "$(date -Is) OK dev refreshed web=${dev_web_ip} stratum=${dev_stratum_ip}"
    fi
else
    echo "$(date -Is) SKIP dev (web=${dev_web_ip:-?} stratum=${dev_stratum_ip:-?})" >&2
fi

# ---- prod (api only, ungated) ----
prod_stratum_ip=$(container_ip "stratum-${PROD_UUID}" || true)

if [[ -n "${prod_stratum_ip:-}" ]]; then
    new_prod=$(cat <<EOF
# Auto-generated by /usr/local/bin/hashden-update-dev-lockdown.sh — do not hand-edit.
# Source of truth: infrastructure/coolify/traefik-hashden-api-routes.yaml in the repo.
# Container IP refreshed on every run; updated $(date -Is).

http:
  routers:
    hashden-prod-api:
      entryPoints:
        - https
      rule: "Host(\`api.hashden.app\`)"
      service: hashden-prod-api-svc
      priority: 1000
      tls:
        certResolver: letsencrypt

  services:
    hashden-prod-api-svc:
      loadBalancer:
        servers:
          - url: "http://${prod_stratum_ip}:3334"
EOF
)
    if [[ ! -f "$PROD_TARGET" ]] || ! diff -q <(echo "$new_prod") "$PROD_TARGET" >/dev/null 2>&1; then
        echo "$new_prod" > "$PROD_TARGET"
        echo "$(date -Is) OK prod refreshed api stratum=${prod_stratum_ip}"
    fi
else
    echo "$(date -Is) SKIP prod (stratum=${prod_stratum_ip:-?})" >&2
fi
